# Form implementation generated from reading ui file 'Dinidex_alternative_main_window_only.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DiniDex(object):
    def setupUi(self, DiniDex):
        DiniDex.setObjectName("DiniDex")
        DiniDex.resize(919, 221)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/icone_programa.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DiniDex.setWindowIcon(icon)
        DiniDex.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(DiniDex)
        self.centralwidget.setObjectName("centralwidget")
        self.pokemon_logo = QtWidgets.QWidget(self.centralwidget)
        self.pokemon_logo.setGeometry(QtCore.QRect(0, -40, 300, 200))
        self.pokemon_logo.setStyleSheet("image: url(:/Images/pokemon_logo.png);\n"
"background:transparent;")
        self.pokemon_logo.setObjectName("pokemon_logo")
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 941, 871))
        self.background.setStyleSheet("background-color: rgb(206, 76, 62);\n"
"\n"
"")
        self.background.setObjectName("background")
        self.search_bar = QtWidgets.QLineEdit(self.background)
        self.search_bar.setGeometry(QtCore.QRect(260, 130, 651, 40))
        self.search_bar.setStyleSheet("color: rgb(68, 68, 68);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.search_bar.setObjectName("search_bar")
        self.background.raise_()
        self.pokemon_logo.raise_()
        DiniDex.setCentralWidget(self.centralwidget)

        self.retranslateUi(DiniDex)
        QtCore.QMetaObject.connectSlotsByName(DiniDex)

    def retranslateUi(self, DiniDex):
        _translate = QtCore.QCoreApplication.translate
        DiniDex.setWindowTitle(_translate("DiniDex", "Dinidex - A simple Pokedex"))
        self.search_bar.setText(_translate("DiniDex", "Digite o nome ou o número correspondente ao POKEDEX do pokemon."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiniDex = QtWidgets.QMainWindow()
    ui = Ui_DiniDex()
    ui.setupUi(DiniDex)
    DiniDex.show()
    sys.exit(app.exec())
